name: 'Install pyosmium dependencies'

runs:
    using: "composite"

    steps:
        - name: Install pip dependencies
          run: |
              python -m pip install --upgrade pip
              pip install nose shapely setuptools
          shell: bash

        - name: Install package dependencies
          run: |
              git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git contrib/libosmium
              git clone --quiet --depth 1 https://github.com/mapbox/protozero.git contrib/protozero
              git clone --quiet --depth 1 https://github.com/pybind/pybind11.git contrib/pybind11
          shell: bash
