import typing

from .osm import WayNodeList, Area, Location, Node, NodeRef


class BaseFactory:
    epsg: int
    proj_string: str

    def create_linestring(self, list: WayNodeList, use_nodes: use_nodes, direction: direction) -> str: ...

    def create_multipolygon(self, area: Area) -> str: ...

    @typing.overload
    def create_point(self, location: Location) -> str: ...

    @typing.overload
    def create_point(self, node: Node) -> str: ...

    @typing.overload
    def create_point(self, ref: NodeRef) -> str: ...


class GeoJSONFactory(BaseFactory): ...


class WKBFactory(BaseFactory): ...


class WKTFactory(BaseFactory): ...


def haversine_distance(list: WayNodeList) -> float: ...


class direction:
    BACKWARD: direction = ...
    FORWARD: direction = ...
    names: typing.Dict[str, direction] = ...
    values: typing.Dict[int, direction] = ...


class use_nodes:
    ALL: use_nodes = ...
    UNIQUE: use_nodes = ...
    names: typing.Dict[str, use_nodes] = ...
    values: typing.Dict[int, use_nodes] = ...
