# SPDX-License-Identifier: BSD-2-Clause
#
# This file is part of pyosmium. (https://osmcode.org/pyosmium/)
#
# Copyright (C) 2024 Sarah Hoffmann <lonvia@denofr.de> and others.
# For a full list of authors see the git log.
from typing import Any, Union
from typing_extensions import Buffer

from typing import overload

from .osm import Box, osm_entity_bits

class File:
    has_multiple_object_versions: bool
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, filename: str, format: str) -> None: ...
    def parse_format(self, arg0: str) -> None: ...

class FileBuffer:
    def __init__(self, buf: Buffer, format: str) -> None:...

class Header:
    has_multiple_object_versions: bool
    def __init__(self) -> None: ...
    def add_box(self, box: Box) -> Header: ...
    def box(self) -> Box: ...
    def get(self, key: str, default: str = ...) -> str: ...
    def set(self, key: str, value: str) -> None: ...

class Reader:
    @overload
    def __init__(self, filename: Union[str, FileBuffer, File]) -> None: ...
    @overload
    def __init__(self, filename: Union[str, FileBuffer, File], types: osm_entity_bits) -> None: ...
    def close(self) -> None: ...
    def eof(self) -> bool: ...
    def header(self) -> Header: ...
    def __enter__(self) -> 'Reader':...
    def __exit__(self, *args: Any) -> None:...

class Writer:
    @overload
    def __init__(self, ffile: Union[str, File]) -> None: ...
    @overload
    def __init__(self, ffile: Union[str, File], header: Header) -> None: ...
    def close(self) -> int: ...
